//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DTXProxyChannel;

@interface _DTXProxy : NSObject
{
    DTXProxyChannel *_proxyChannel;
}

- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)initWithChannel:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;

@end

