//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <DTXConnectionServices/DTXConnectionRemoteReceiveQueueCalls-Protocol.h>
#import <DTXConnectionServices/DTXMessenger-Protocol.h>

@class DTXChannel, DTXMessageParser, DTXMessageTransmitter, DTXResourceTracker, DTXTransport, NSDictionary, NSMutableArray, NSMutableDictionary, NSSet, NSString;
@protocol DTXBlockCompressor, OS_dispatch_queue, OS_dispatch_semaphore;

@interface DTXConnection : NSObject <DTXConnectionRemoteReceiveQueueCalls, DTXMessenger>
{
    NSString *_label;
    NSObject<OS_dispatch_queue> *_outgoing_message_queue;
    NSObject<OS_dispatch_queue> *_outgoing_control_queue;
    DTXTransport *_controlTransport;
    NSSet *_permittedBlockCompressors;
    NSObject<OS_dispatch_queue> *_receive_queue;
    NSObject<OS_dispatch_queue> *_handler_queue;
    unsigned int _nextChannelCode;
    NSMutableDictionary *_channelsByCode;
    NSMutableDictionary *_unconfiguredChannelsByCode;
    NSMutableDictionary *_handlersByIdentifier;
    NSMutableArray *_protocolHandlers;
    NSMutableDictionary *_localCapabilityVersions;
    NSMutableDictionary *_localCapabilityClasses;
    NSDictionary *_remoteCapabilityVersions;
    NSMutableArray *_capabilityOverrideBlocks;
    DTXResourceTracker *_resourceTracker;
    DTXResourceTracker *_incomingResourceTracker;
    NSObject<OS_dispatch_semaphore> *_firstMessageSem;
    DTXMessageParser *_incomingParser;
    DTXMessageTransmitter *_outgoingTransmitter;
    DTXChannel *_defaultChannel;
    BOOL _tracer;
    BOOL _remoteTracer;
    int _connectionIndex;
    CDUnknownBlockType _channelHandler;
    unsigned long long _logMessageCallstackSizeThreshold;
    int _remoteCompressionCapabilityVersion;
    int _newChannelCompressionHint;
    int _compressionTypeForUnspecified;
    unsigned long long _compressionMinSizeThreshold;
    id <DTXBlockCompressor> _compressor;
}

+ (id)connectionToAddress:(id)arg1;
+ (void)initialize;
+ (void)observeDecompressionExceptionLogging:(CDUnknownBlockType)arg1;
+ (void)registerTransport:(Class)arg1 forScheme:(id)arg2;
- (void).cxx_destruct;
- (BOOL)_addHandler:(CDUnknownBlockType)arg1 forMessage:(unsigned int)arg2 channel:(id)arg3;
- (void)_cancelInternal:(CDUnknownBlockType)arg1;
- (void)_channelCanceled:(unsigned int)arg1;
- (void)_handleMessageParseException:(id)arg1 forChannelCode:(unsigned int)arg2 messageID:(unsigned int)arg3 fragmentCount:(unsigned int)arg4 withPayloadBytes:(const void *)arg5 ofLength:(unsigned long long)arg6;
- (void)_handleMissingRemoteCapabilities;
- (void)_handleProxyRequestForInterface:(id)arg1 interfaceName:(id)arg2 peerInterface:(id)arg3 peerInterfaceName:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (id)_makeProxyChannelWithRemoteInterface:(id)arg1 remoteInterfaceName:(id)arg2 exportedInterface:(id)arg3 exportedInterfaceName:(id)arg4;
- (void)_notifyCompressionHint:(unsigned int)arg1 forChannelCode:(unsigned int)arg2;
- (void)_notifyOfPublishedCapabilities:(id)arg1;
- (void)_receiveQueueSetCompressionHint:(unsigned int)arg1 onChannel:(id)arg2;
- (void)_requestChannelWithCode:(unsigned int)arg1 identifier:(id)arg2;
- (void)_routeMessage:(id)arg1;
- (void)_scheduleMessage:(id)arg1 toChannel:(id)arg2;
- (id)_sendHeartbeatAsyncWithTimeout:(double)arg1;
- (void)_setTracerState:(unsigned int)arg1;
- (void)_setupWireProtocols;
- (id)_testing_remoteCapabilityVersions;
- (void)_unregisterChannel:(id)arg1;
@property(readonly, nonatomic) int atomicConnectionNumber; // @synthesize atomicConnectionNumber=_connectionIndex;
- (void)cancel;
- (void)cancelWithSerializedTransport:(CDUnknownBlockType)arg1;
- (void)dealloc;
@property(readonly, retain, nonatomic) DTXChannel *defaultChannel;
@property(readonly, copy) NSString *description;
- (void)handleProxyRequestForInterface:(id)arg1 interfaceName:(id)arg2 peerInterface:(id)arg3 peerInterfaceName:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (void)handleProxyRequestForInterface:(id)arg1 peerInterface:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)initWithTransport:(id)arg1;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (id)localCapabilities;
- (id)makeChannelWithIdentifier:(id)arg1;
- (id)makeProxyChannelWithRemoteInterface:(id)arg1 exportedInterface:(id)arg2;
- (id)makeProxyChannelWithRemoteInterface:(id)arg1 remoteInterfaceName:(id)arg2 exportedInterface:(id)arg3 exportedInterfaceName:(id)arg4;
@property(nonatomic) unsigned long long maximumEnqueueSize;
- (void)overridePermittedBlockCompressors:(id)arg1;
- (double)preflightSynchronouslyWithTimeout:(double)arg1;
- (void)publishCapability:(id)arg1 withVersion:(int)arg2 forClass:(Class)arg3;
- (BOOL)publishCapability:(id)arg1 withVersion:(int)arg2 forClass:(Class)arg3 error:(id *)arg4;
- (void)publishServicesInImagePath:(id)arg1;
- (id)publishedAddresses;
- (void)registerCapabilityOverrideBlock:(CDUnknownBlockType)arg1;
- (void)registerDisconnectHandler:(CDUnknownBlockType)arg1;
- (int)remoteCapabilityVersion:(id)arg1;
- (id)remoteCapabilityVersions;
@property(nonatomic) BOOL remoteTracer; // @synthesize remoteTracer=_remoteTracer;
- (void)replaceCompressorForCompression:(id)arg1;
- (void)replaceCompressorForDecompression:(id)arg1;
- (void)resume;
- (void)sendControlAsync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)sendControlSync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (BOOL)sendMessage:(id)arg1 fromChannel:(id)arg2 sendMode:(int)arg3 syncWithReply:(BOOL)arg4 replyHandler:(CDUnknownBlockType)arg5;
- (void)sendMessage:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (BOOL)sendMessageAsync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)sendMessageSync:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
- (void)setChannelHandler:(CDUnknownBlockType)arg1;
- (void)setCompressionHint:(int)arg1 forChannel:(id)arg2;
- (void)setDispatchTarget:(id)arg1;
- (void)setMessageHandler:(CDUnknownBlockType)arg1;
@property(nonatomic) BOOL tracer; // @synthesize tracer=_tracer;
- (void)suspend;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

