//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DTXConnectionServices/DTXTransport.h>

@class NSObject;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface DTXMachTransport : DTXTransport
{
    unsigned int _receivePort;
    unsigned int _sendPort;
    NSObject<OS_dispatch_queue> *_inputQueue;
    NSObject<OS_dispatch_queue> *_outputQueue;
    NSObject<OS_dispatch_source> *_listenSource;
    NSObject<OS_dispatch_source> *_deadPortSource;
    CDUnknownBlockType _disconnectBlock;
    struct DTXMachMessage *_sendBuffer;
    unsigned int _bufferedLength;
}

+ (id)_legacyFileDescriptorHandshakeWithReceivePort:(unsigned int)arg1;
+ (id)_legacyFileDescriptorHandshakeWithSendPort:(unsigned int)arg1;
+ (id)fileDescriptorHandshakeWithReceivePort:(unsigned int)arg1;
+ (id)fileDescriptorHandshakeWithSendPort:(unsigned int)arg1;
+ (id)schemes;
- (void).cxx_destruct;
- (BOOL)_setupWithSendPort:(unsigned int)arg1 receivePort:(unsigned int)arg2 disconnectBlock:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (void)disconnect;
- (id)init;
- (id)initWithReceiveRight:(unsigned int)arg1 sendRight:(unsigned int)arg2 disconnectBlock:(CDUnknownBlockType)arg3;
- (id)initWithRemoteAddress:(id)arg1;
- (id)initWithXPCRepresentation:(id)arg1;
- (id)localAddresses;
- (id)serializedXPCRepresentation;
- (unsigned long long)transmit:(const void *)arg1 ofLength:(unsigned long long)arg2;

@end

