//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class DTXChannel, NSSet, Protocol;

@interface DTXProxyChannel : NSObject
{
    Protocol *_remoteInterface;
    Protocol *_exportedInterface;
    DTXChannel *_channel;
    NSSet *_additionalAllowedClassesForProtocolMethods;
    _Atomic _Bool _hasProcessedMessage;
}

- (void).cxx_destruct;
- (id)_allowedClassesForArgumentsOfRemoteInterfaceSelector:(SEL)arg1 methodSignature:(id)arg2;
- (id)_allowedClassesForReturnValues;
- (void)_sendInvocationMessage:(id)arg1;
- (id)_validateDispatch:(id)arg1;
@property(retain, nonatomic) NSSet *additionalAllowedClassesForProtocolMethods; // @synthesize additionalAllowedClassesForProtocolMethods=_additionalAllowedClassesForProtocolMethods;
- (void)cancel;
@property(retain, nonatomic) DTXChannel *channel; // @synthesize channel=_channel;
- (id)initWithChannel:(id)arg1 remoteProtocol:(id)arg2 localProtocol:(id)arg3;
@property(retain) Protocol *remoteInterface; // @synthesize remoteInterface=_remoteInterface;
@property(readonly) id remoteObjectProxy;
- (void)setExportedObject:(id)arg1 queue:(id)arg2;

@end

