//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, Protocol;

@interface DTXProxyRequestHandler : NSObject
{
    Protocol *_publishedProtocol;
    NSString *_publishedProtocolName;
    Protocol *_peerProtocol;
    NSString *_peerProtocolName;
    CDUnknownBlockType _handlerBlock;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *channelIdentifier;
@property(readonly, copy) CDUnknownBlockType handlerBlock; // @synthesize handlerBlock=_handlerBlock;
- (id)initWithPublishedProtocol:(id)arg1 publishedProtocolName:(id)arg2 peerProtocol:(id)arg3 peerProtocolName:(id)arg4 handlerBlock:(CDUnknownBlockType)arg5;
- (BOOL)matchesPublishedProtocolName:(id)arg1 peerProtocolName:(id)arg2;
@property(readonly) Protocol *peerProtocol; // @synthesize peerProtocol=_peerProtocol;
@property(readonly, copy) NSString *peerProtocolName; // @synthesize peerProtocolName=_peerProtocolName;
@property(readonly) Protocol *publishedProtocol; // @synthesize publishedProtocol=_publishedProtocol;
@property(readonly, copy) NSString *publishedProtocolName; // @synthesize publishedProtocolName=_publishedProtocolName;

@end

