//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface DTXResourceTracker : NSObject
{
    unsigned long long _total;
    unsigned long long _maxChunk;
    unsigned long long _used;
    unsigned int _waiting;
    unsigned int _acquireNum;
    int _suspendCount;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_semaphore> *_acqSem;
    DTXResourceTracker *_parentTracker;
    BOOL _log;
}

- (void).cxx_destruct;
- (unsigned int)acquireSize:(unsigned long long)arg1;
- (void)forceAcquireSize:(unsigned long long)arg1;
- (id)init;
@property(nonatomic) BOOL log; // @synthesize log=_log;
@property(nonatomic) unsigned long long maxChunkSize;
- (void)releaseSize:(unsigned long long)arg1;
- (void)resumeLimits;
@property(nonatomic) unsigned long long totalSize;
- (void)suspendLimits;

@end

